version: '3'
services:
  dynamodb:
    restart: always
    image: amazon/dynamodb-local

  app:
    build: .
    command: python app.py
    depends_on:
      - dynamodb
    restart: always
    ports:
      - "5000:5000"
    volumes:
      - .:/wordcount

