version: '3'
services:
  dynamoDB:
    restart: always
    image: amazon/dynamodb-local
    ports:
      - "8000:8000"

  lambda:
    image: lambci/lambda:python3.7
    command: lambda_function.lambda_handler
    # restart: always
    volumes:
      - .:/var/task
    ports:
      - "3000:3000"
    depends_on:
      - dynamoDB
